#CAF,INDICATEUR SUR LA PART DES PRESTATIONS DANS LES RESSOURCES DES FOYERS ALLOCATAIRES PAR COMMUNE,
#DependancePrestaCom,http://data.caf.fr/dataset/indicateur-sur-la-part-des-prestations-dans-les-ressources-des-foyers-allocataires-par-commune

#CAF,BENEFICIAIRES BAS REVENUS,
#BasrevnuCom,http://data.caf.fr/dataset/beneficiaire-bas-revenus

#CAF,POPULATION DES FOYERS ALLOCATAIRES PAR COMMUNE,
#NIVCOMTOTAL2009,http://data.caf.fr/dataset/population-des-foyers-allocataires-par-commune

#CAF,REPARTITION DES FOYERS ALLOCATAIRES SELON LE TYPE DE FAMILLE PAR COMMUNE,
#ConfigFamiliale,http://data.caf.fr/dataset/repartition-des-foyers-allocataires-selon-le-type-de-famille-par-commune

#CAF,DENOMBREMENT ET REPARTITION DES FOYERS ALLOCATAIRES SELON L'AGE DU RESPONSABLE,
#TrancheAge,http://data.caf.fr/dataset/denombrement-et-repartition-des-foyers-allocataires-selon-l-age-du-responsable


#CAF,POPULATION DES FOYERS ALLOCATAIRES PERCEVANT UNE AIDE PERSONNELLE AU LOGEMENT,
#LOGCom,http://data.caf.fr/dataset/population-des-foyers-allocataires-percevant-une-aide-personnelle-au-logement

#CAF, FOYERS ALLOCATAIRES PERCEVANT LA PRESTATION D'ACCUEIL DU JEUNE ENFANT PAJE PAR COMMUNE,
#PAJECom,http://data.caf.fr/dataset/foyers-allocataires-percevant-la-prestation-d-accueil-du-jeune-enfant-paje-par-commune

#CAF, POPULATION DES FOYERS ALLOCATAIRES PERCEVANT LE REVENU DE SOLIDARITE,
#RSAPersCom,http://data.caf.fr/dataset/population-des-foyers-allocataires-percevant-le-revenu-de-solidarite

#CAF, PERSONNES AYANT UN DROIT VERSABLE A L'ALLOCATION AUX ADULTES HANDICAPES,
#AAHCom,http://data.caf.fr/dataset/personnes-ayant-un-droit-versable-a-l-allocation-aux-adultes-handicapes

#CAF,REPARTITION PAR TRANCHE D'AGE DES ENFANTS COUVERTS PAR DES PRESTATIONS CAF,
#EnfantAgeCom,http://data.caf.fr/dataset/repartition-par-tranche-d-age-des-enfants-couverts-par-des-prestations-caf

#CAF,NOMBRE D'ENFANTS COUVERTS PAR L'ALLOCATION D'EDUCATION DE L'ENFANT HANDICAPE AEEH PAR COMMUNE
#enfantAEEH,http://data.caf.fr/dataset/nombre-d-enfants-couverts-par-l-allocation-d-education-de-l-enfant-handicape-aeeh-par-commune

#CAF,FOYERS ALLOCATAIRES PERCEVANT LE REVENU DE SOLIDARITE ACTIVE RSA PAR COMMUNE,
#RSACom,http://data.caf.fr/dataset/foyers-allocataires-percevant-le-revenu-de-solidarite-active-rsa-par-commune


#CAF,FOYERS ALLOCATAIRES PERCEVANT UNE PRESTATION ENFANCE ET JEUNESSE AF CF ASF AEEH et ARS par commune,
#EJCom,http://data.caf.fr/dataset/foyers-allocataires-percevant-une-prestation-enfance-et-jeunesse-af-cf-asf-aeeh-et-ars-par-comm


#CAF,POPULATION DES FOYERS ALLOCATAIRES,
#LogPersPrestaCom,http://data.caf.fr/dataset/population-des-foyers-allocatair


#CAF,NOMBRE D'ENFANTS COUVERTS PAR L'ALLOCATION DE RENTREE SCOLAIRE ARS PAR COMMUNE
#EnfantARS,http://data.caf.fr/dataset/nombre-denfants-couverts-par-l-allocation-de-rentree-scolaire-ars-par-commune
caf_open_dictionnary = {
"NB_allocataires" : "NOMBRE TOTAL DE FOYERS ALLOCATAIRES DE LA BRANCHE FAMILLE",
"TR50PFRB" :	"NOMBRE DE FOYERS ALLOCATAIRES DONT LES RESSOURCES SONT CONSTITUEES A 50% OU PLUS DES PRESTATIONS CAF",
"TR100PFRB" : "NOMBRE DE FOYERS ALLOCATAIRES DONT LES RESSOURCES SONT CONSTITUEES A 100% DES PRESTATIONS CAF",
"NB_allocataires_ress":"NOMBRE DE FOYERS ALLOCATAIRES DE REFERENCE POUR CALCUL DES BAS REVENUS",
"NB_pers_couv_ress":"NOMBRE DE PERSONNES COUVERTES DE REFERENCE POUR CALCUL DES BAS REVENUS",
"ALL_bas_revenu":"NOMBRE TOTAL DE FOYERS ALLOCATAIRES BAS REVENUS",
"Pers_bas_revenu":"NOMBRE TOTAL DE PERSONNES COUVERTES PAR LES FOYERS BAS REVENUS",
"NB_Pers_par_Foyer_Alloc":"NOMBRE DE PERSONNES COUVERTES PAR LA BRANCHE FAMILLE",
"NB_Enfants":"NOMBRE D'ENFANTS COUVERTS",
"NB_Allocataires":"NOMBRE TOTAL DE FOYERS ALLOCATAIRES DE LA BRANCHE FAMILLE",
"COUP_0_ENF":"NOMBRE DE FOYERS ALLOCATAIRES COUPLES SANS ENFANT",
"COUP_1_ENF":"NOMBRE DE FOYERS ALLOCATAIRES COUPLES AVEC 1 ENFANT",
"COUP_2_ENF":"NOMBRE DE FOYERS ALLOCATAIRES COUPLES AVEC 2 ENFANTS",
"COUP_3_ENF":"NOMBRE DE FOYERS ALLOCATAIRES COUPLES AVEC 3 ENFANTS",
"COUP_4plus_ENF":"NOMBRE DE FOYERS ALLOCATAIRES COUPLES AVEC 4 A X ENFANTS",
"Homme_Isole":"NOMBRE DE FOYERS ALLOCATAIRES MESSIEURS ISOLES",
"Femme_Isolee":"NOMBRE DE FOYERS ALLOCATAIRES MESDAMES ISOLEES",
"MONO_1_ENF":"NOMBRE DE FOYERS ALLOCATAIRES MONOPARENTS AVEC 1 ENFANT",
"MONO_2_ENF":"NOMBRE DE FOYERS ALLOCATAIRES MONOPARENTS AVEC 2 ENFANTS",
"MONO_3_ENF":"NOMBRE DE FOYERS ALLOCATAIRES MONOPARENTS AVEC 3 ENFANTS",
"MONO_4plus_ENF":"NOMBRE DE FOYERS ALLOCATAIRES MONOPARENTS AVEC 4 A X ENFANTS",
"NB_Allocataires" : "NOMBRE TOTAL DE FOYERS ALLOCATAIRES DE LA BRANCHE FAMILLE",
"ALL0A19" :"NOMBRE DE FOYERS ALLOCATAIRES DONT LE TITUTAILRE DU DOSSIER EST AGE DE MOINS DE 20 ANS",
"ALL20A24" : "NOMBRE DE FOYERS ALLOCATAIRES DONT LE TITUTAILRE DU DOSSIER EST AGE DE 20 A 24 ANS",
"ALL25A29" : "NOMBRE DE FOYERS ALLOCATAIRES DONT LE TITUTAILRE DU DOSSIER EST AGE DE 25 A 29 ANS",
"ALL30A39" : "NOMBRE DE FOYERS ALLOCATAIRES DONT LE TITUTAILRE DU DOSSIER EST AGE DE 30 A 39 ANS",
"ALL40A49" : "NOMBRE DE FOYERS ALLOCATAIRES DONT LE TITUTAILRE DU DOSSIER EST AGE DE 40 A 49 ANS",
"ALL50A54*" : "NOMBRE DE FOYERS ALLOCATAIRES DONT LE TITUTAILRE DU DOSSIER EST AGE DE 50 A 54 ANS",
"ALL55A59*" : "NOMBRE DE FOYERS ALLOCATAIRES DONT LE TITUTAILRE DU DOSSIER EST AGE DE 55 A 59 ANS",
"ALL60A64*" : "NOMBRE DE FOYERS ALLOCATAIRES DONT LE TITUTAILRE DU DOSSIER EST AGE DE 60 A 64 ANS",
"ALL65A69*" : "NOMBRE DE FOYERS ALLOCATAIRES DONT LE TITUTAILRE DU DOSSIER EST AGE DE 65 A 69 ANS",
"ALL70AX*" : "NOMBRE DE FOYERS ALLOCATAIRES DONT LE TITUTAILRE DU DOSSIER EST AGE DE 70 ANS OU PLUS",
"ALLAGEX" : "NOMBRE DE FOYERS ALLOCATAIRES DONT LE TITUTAILRE DU DOSSIER EST D'AGE INCONNU",
"total_allocataires":"NOMBRE TOTAL DE FOYERS ALLOCATAIRES DE LA BRANCHE FAMILLE",
"total_allocataires_logement":"NOMBRE TOTAL DE FOYERS ALLOCATAIRES BENEFICIAIRE D'UNE AIDE AU LOGEMENT",
"total_ALF":"NOMBRE TOTAL DE FOYERS ALLOCATAIRES BENEFICIAIRE DE L'ALF",
"total_ALS":"NOMBRE TOTAL DE FOYERS ALLOCATAIRES BENEFICIAIRE DE L'ALS",
"total_APL":"NOMBRE TOTAL DE FOYERS ALLOCATAIRES BENEFICIAIRE DE L'APL",
"locataire_ALF":"NOMBRE DE FOYERS ALLOCATAIRES EN LOCATION OU EN FOYER BENEFICIAIRE DE L'ALF",
"locataire_ALS":"NOMBRE DE FOYERS ALLOCATAIRES EN LOCATION OU EN FOYER BENEFICIAIRE DE L'ALS",
"locataire_APL":"NOMBRE DE FOYERS ALLOCATAIRES EN LOCATION OU EN FOYER BENEFICIAIRE DE L'APL",
"proprietaire_ALF":"NOMBRE DE FOYERS ALLOCATAIRES PROPRIETAIRE BENEFICIAIRE DE L'ALF",
"proprietaire_ALS":"NOMBRE DE FOYERS ALLOCATAIRES PROPRIETAIRE BENEFICIAIRE DE L'ALF",
"proprietaire_APL":"NOMBRE DE FOYERS ALLOCATAIRES PROPRIETAIRE BENEFICIAIRE DE L'ALF",
"total_locataire":"NOMBRE TOTAL DE FOYERS ALLOCATAIRES EN LOCATION OU EN FOYER BENEFICIAIRE D'UNE AIDE AU LOGEMENT",
"total_proprietaire":"NOMBRE TOTAL DE FOYERS ALLOCATAIRES PROPRIETAIRE BENEFICIAIRE D'UNE AIDE AU LOGEMENT",
"NB_Allocataires":"NOMBRE TOTAL DE FOYERS ALLOCATAIRES DE LA BRANCHE FAMILLE",
"ALL_PAJE":"NOMBRE DE FOYERS ALLOCATAIRES PAJE VERSABLE",
"ALL_PRIM":"NOMBRE DE FOYERS ALLOCATAIRES PRIME NAISSANCE OU ADOPTION VERSEES",
"ALL_BASEP":"NOMBRE DE FOYERS ALLOCATAIRES AVEC DROIT BASE PAJE VERSABLE",
"ALL_CMG":"NOMBRE DE FOYERS ALLOCATAIRES CMG VERSABLE",
"ALL_CMG_ASMA":"NOMBRE DE FOYERS ALLOCATAIRES CMG ASSISTANTE MATERNELLE VERSABLE",
"ALL_CMG_DOM":"NOMBRE DE FOYERS ALLOCATAIRES CMG GARDE A DOMICILE VERSABLE",
"ALL_CMG_A":"NOMBRE DE FOYERS ALLOCATAIRES CMG STRUCTURE (ENTREPRISE OU ASSOCIATION) VERSABLE",
"ALL_Clca":"NOMBRE DE FOYERS ALLOCATAIRES CLCA VERSABLE",
"NB_Pers_par_Foyer_Alloc":"NOMBRE DE PERSONNES COUVERTES PAR UNE PRESTATION DE LA BRANCHE FAMILLE",
"NB_Pers_couv_RSA":"NOMBRE DE PERSONNES COUVERTES PAR LE RSA",
"RSA_SOCLE_non_Majore_Pers_couv":"NOMBRE DE PERSONNES COUVERTES PAR LE RSA SOCLE SANS MAJORATION VERSABLE",
"RSA_SOCLE_Majore_Pers_couv":"NOMBRE DE PERSONNES COUVERTES PAR LE RSA SOCLE AVEC MAJORATION VERSABLE",
"RSA_activite_Pers_couv":"NOMBRE DE PERSONNES COUVERTES PAR LE RSA ACTIVITE VERSABLE",
"NB_Allocataires":"NOMBRE TOTAL DE FOYERS ALLOCATAIRES DE LA BRANCHE FAMILLE",
"ALL_AAH":"NOMBRE D'ALLOCATAIRES AVEC AAH VERSABLE",
"NB_enfants":"NOMBRE D'ENFANTS BENEFICIAIRES D'AU MOINS UNE PRESTATION CAF VERSABLE",
"NB_Enfants_0_2_ans":"NOMBRE D'ENFANTS DE 0 A 2 ANS, BENEFICIAIRES D'AU MOINS UNE PRESTATION CAF VERSABLE",
"NB_Enfants_3_5_ans":"NOMBRE D'ENFANTS DE 3 A 5 ANS, BENEFICIAIRES D'AU MOINS UNE PRESTATION CAF VERSABLE",
"NB_Enfants_6_11_ans":"NOMBRE D'ENFANTS DE 6 A 11 ANS, BENEFICIAIRES D'AU MOINS UNE PRESTATION CAF VERSABLE",
"NB_Enfants_12_15_ans":"NOMBRE D'ENFANTS DE 12 A 15 ANS, BENEFICIAIRES D'AU MOINS UNE PRESTATION CAF VERSABLE",
"NB_Enfants_16_17_ans":"NOMBRE D'ENFANTS DE 16 A 17 ANS, BENEFICIAIRES D'AU MOINS UNE PRESTATION CAF VERSABLE",
"NB_Enfants_18_19_ans":"NOMBRE D'ENFANTS DE 18 A 19 ANS, BENEFICIAIRES D'AU MOINS UNE PRESTATION CAF VERSABLE",
"NB_Enfants_20_24_ans":"NOMBRE D'ENFANTS DE 20 A 24 ANS, BENEFICIAIRES D'AU MOINS UNE PRESTATION CAF VERSABLE",
"NB_enfant_AEEH":"NOMBRE D'ENFANTS BENEFICIAIRES DE L'AEEH VERSABLE",
"AEEH_0A2":"NOMBRE D'ENFANTS DE 0 A 2 ANS BENEFICIAIRES DE L'AEEH VERSABLE",
"AEEH_3A5":"NOMBRE D'ENFANTS DE 3 A 5 ANS BENEFICIAIRES DE L'AEEH VERSABLE",
"AEEH_6A11":"NOMBRE D'ENFANTS DE 6 A 11 ANS BENEFICIAIRES DE L'AEEH VERSABLE",
"AEEH_12A15":"NOMBRE D'ENFANTS DE 12 A 15 ANS BENEFICIAIRES DE L'AEEH VERSABLE",
"AEEH_16A17":"NOMBRE D'ENFANTS DE 16 A 17 ANS BENEFICIAIRES DE L'AEEH VERSABLE",
"AEEH_18A20":"NOMBRE D'ENFANTS DE 18 A 20 ANS BENEFICIAIRES DE L'AEEH VERSABLE",
"NB_Allocataires":"NOMBRE TOTAL DE FOYERS ALLOCATAIRES DE LA BRANCHE FAMILLE",
"NB_allocataire_RSA":"NOMBRE TOTAL DE FOYERS ALLOCATAIRES RSA",
"Dont_RSA_jeune":"NOMBRE DE FOYERS ALLOCATAIRES RSA JEUNE",
"RSA_SOCLE_non_Majore":"NOMBRE DE FOYERS ALLOCATAIRES RSA SOCLE SANS MAJORATION VERSABLE",
"RSA_SOCLE_Majore":"NOMBRE DE FOYERS ALLOCATAIRES RSA SOCLE AVEC MAJORATION VERSABLE",
"RSA_activite":"NOMBRE DE FOYERS ALLOCATAIRES RSA ACTIVITE VERSABLE",
"NB_Allocataires":"NOMBRE TOTAL DE FOYERS ALLOCATAIRES DE LA BRANCHE FAMILLE",
"ALL_AF":"NOMBRE DE FOYERS ALLOCATAIRES AVEC AF VERSABLE",
"ALL_CF":"NOMBRE DE FOYERS ALLOCATAIRES AVEC CF VERSABLE",
"ALL_ARS":"NOMBRE DE FOYERS ALLOCATAIRES AVEC ARS VERSABLE",
"ALL_ASF":"NOMBRE DE FOYERS ALLOCATAIRES AVEC ASF VERSABLE",
"ALL_AEEH":"NOMBRE DE FOYERS ALLOCATAIRES AVEC AEEH VERSABLE",
"NB_Pers_Couv_Al":"NOMBRE DE PERSONNES COUVERTES PAR UNE AIDE AU LOGEMENT VERSABLE",
"Pers_Couv_Al_ALF":"NOMBRE DE PERSONNES COUVERTES PAR ALF VERSABLE",
"Pers_Couv_Al_ALS":"NOMBRE DE PERSONNES COUVERTES PAR ALS VERSABLE",
"Pers_Couv_Al_APL":"NOMBRE DE PERSONNES COUVERTES PAR APL VERSABLE",
"NB_enfant_ARS":"NOMBRE D'ENFANTS OUVRANT DROIT A L'ARS VERSABLE",
"ARS_5A10":"NOMBRE D'ENFANTS DE 5 A 10 ANS, OUVRANT DROIT A L'ARS VERSABLE",
"ARS_11A14":"NOMBRE D'ENFANTS DE 11 A 14 ANS, OUVRANT DROIT A L'ARS VERSABLE",
"ARS_15A17":"NOMBRE D'ENFANTS DE 15 A 17 ANS, OUVRANT DROIT A L'ARS VERSABLE"
}